name: Java CI with Maven

on:
  pull_request:
    branches:
      - '*'
    push:
      branches:
        - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: 14
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Maven Package
        run: mvn -B clean package --file pom.xml