name: Build

on:
  pull_request:
    branches:
      - '*'
    push:
      branches:
        - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Maven Package
        run: mvn -B clean package